-------------------------------------------------------------------------------
Test set: net.mooctest.Othello_sub_5_36_Test
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in net.mooctest.Othello_sub_5_36_Test
test_8186(net.mooctest.Othello_sub_5_36_Test)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: Expecting exception: ArrayIndexOutOfBoundsException
	at net.mooctest.Othello_sub_5_36_Test.test_8186(Othello_sub_5_36_Test.java:99)

